Refactor duplicated CI code (#639)
Close #637

diff --git a/.github/workflows/diff-check.yml b/.github/workflows/diff-check.yml
--- a/.github/workflows/diff-check.yml
+++ b/.github/workflows/diff-check.yml
@@ -5,10 +5,12 @@ on:
   push:
     branches:
       - master
+  pull_request:
+  merge_group:
 
 jobs:
   tests:
-    name: Diff check and push
+    name: Generate OpenAPI based code
     runs-on: ubuntu-latest
 
     steps:
@@ -55,7 +57,15 @@ jobs:
           diff=$(git --no-pager diff --name-only HEAD)
           echo "DIFF_IS_EMPTY=$([[ -z "$diff" ]] && echo 'true' || echo 'false')" >> $GITHUB_ENV
           echo "CURRENT_DATETIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
-      - if: ${{ env.DIFF_IS_EMPTY != 'true' }}
+      ## Run if diff exists and pull request, and make CI status failure (but allow renovate bot)
+      - if: ${{ github.event_name == 'pull_request' && env.DIFF_IS_EMPTY != 'true' && github.actor != 'renovate[bot]' }}
+        run: |
+          echo "There are changes in the generated codes. Please run 'generate-code.py' and commit the changes." >&2
+          echo "The files with differences are as follows." >&2
+          echo "$(git --no-pager diff --name-only HEAD)" >&2
+          exit 1
+      ## Run if diff exists and event is not pull request, and make PR
+      - if: ${{ github.event_name != 'pull_request' && env.DIFF_IS_EMPTY != 'true' }}
         run: |
           BRANCH_NAME="update-diff-${{ env.CURRENT_DATETIME }}"
           
